{{- if .Values.server.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
spec:
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.server.autoscaling.targetCPUUtilizationPercentage }}
        type: Utilization
    type: Resource
  - external:
      metric:
        name: trino.execution.executor.waiting_splits
        selector:
          matchLabels:
            kube_deployment: {{ template "trino.worker" . }}
      target:
        type: Value
        value: 1k
    type: External
  {{- if .Values.server.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.server.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
